#Travis jobs summary: 
# - 2 x86_64 jobs using gcc/clang
# - 1 windows job using visual studio 2017

language: c

arch:
  - amd64 #x86_64

dist: bionic

compiler:
  - gcc
  - clang

scripts: |-
  #  mkdir build
  #  cd build
  #  cmake ..
  make
  ./jhead ; exit 0
